import { env } from "./env";
import { apiEndpoints } from "../docs/endpoint-registry";
import {
  applyRequestBodyEnumContracts,
  applyRequestBodySchemaContracts,
  applyResponseEnumContracts,
  inferSchema,
  pathParameterExamples,
  queryParameterContracts,
  requestBodyContracts,
  successContracts,
  ticketResponseSchemaContracts,
} from "../docs/openapi-contracts";

type OpenApiPathItem = Record<string, unknown>;
const paths: Record<string, OpenApiPathItem> = {};

const operationKey = (method: string, path: string): string => {
  return `${method.toUpperCase()} ${path}`;
};

const checkoutErrorResponse = (
  description: string,
  examples: Record<string, { summary: string; code: string; message: string }>,
) => ({
  description,
  content: {
    "application/json": {
      schema: {
        type: "object", additionalProperties: false,
        required: ["success", "error", "requestId"],
        properties: {
          success: { type: "boolean", const: false },
          error: {
            type: "object", additionalProperties: false,
            required: ["code", "message"],
            properties: {
              code: { type: "string", enum: Object.values(examples).map((item) => item.code) },
              message: { type: "string" },
            },
          },
          requestId: { type: "string" },
        },
      },
      examples: Object.fromEntries(Object.entries(examples).map(([name, item]) => [name, {
        summary: item.summary,
        value: {
          success: false, error: { code: item.code, message: item.message },
          requestId: "req_01J2EXAMPLE9G7TZ8K4X3",
        },
      }])),
    },
  },
});

const applyTicketResponseSchemaContracts = (
  schema: Record<string, unknown>,
  contracts: Record<string, Record<string, unknown>> | undefined,
): void => {
  for (const [path, override] of Object.entries(contracts || {})) {
    const segments = path.split(".");
    let current = schema;

    segments.forEach((segment, index) => {
      const properties = current.properties as Record<string, Record<string, unknown>>;
      const isArray = segment.endsWith("[]");
      const property = isArray ? segment.slice(0, -2) : segment;
      const last = index === segments.length - 1;

      if (last && isArray) {
        properties[property] = { ...properties[property], items: override };
        return;
      }

      if (last) {
        properties[property] = override;
        return;
      }

      const child = properties[property]!;
      current = isArray ? child.items as Record<string, unknown> : child;
    });
  }
};

for (const endpoint of apiEndpoints) {
  const key = operationKey(endpoint.method, endpoint.path);
  const success = successContracts[key];

  if (!success) {
    throw new Error(`Missing OpenAPI success contract for ${key}`);
  }

  const pathParameters = [...endpoint.path.matchAll(/\{([^}]+)\}/g)].map((match) => {
    const name = match[1] as string;
    const contract = pathParameterExamples[name];
    return {
      name,
      in: "path",
      required: true,
      description: contract?.description || "Resource identifier.",
      schema: name === "orderNumber" && endpoint.path.startsWith("/tickets/")
        ? { ...(contract?.schema || { type: "string" }), pattern: "^CC-\\d+-[A-F0-9]{8}$" }
        : contract?.schema || { type: "string" },
      ...(contract?.example ? {
        example: name === "orderNumber" && endpoint.path.includes("membership-orders")
          ? "CCM-1784370000000-A1B2C3D4"
          : contract.example,
      } : {}),
    };
  });
  const queryParameters = (queryParameterContracts[key] || []).map((parameter) => ({
    name: parameter.name,
    in: "query",
    required: parameter.required || false,
    description: parameter.description,
    schema: parameter.schema,
    ...(parameter.example === undefined ? {} : { example: parameter.example }),
  }));
  const parameters: Array<Record<string, unknown>> = [...pathParameters, ...queryParameters];

  if (endpoint.idempotency) {
    parameters.push({
      name: "Idempotency-Key",
      in: "header",
      required: true,
      description: "A unique 16-128 character key reused only when retrying this exact operation.",
      schema: { type: "string", minLength: 16, maxLength: 128 },
      example: "550e8400-e29b-41d4-a716-446655440000",
    });
  }

  if (endpoint.path === "/webhooks/paystack") {
    parameters.push({
      name: "x-paystack-signature",
      in: "header",
      required: true,
      description: "HMAC-SHA512 signature generated by Paystack over the exact raw request body.",
      schema: { type: "string", pattern: "^[a-fA-F0-9]{128}$" },
      example: "a".repeat(128),
    });
  }

  const successSchema = endpoint.path === "/webhooks/paystack"
    ? {
        type: "object",
        required: ["received"],
        properties: {
          received: { type: "boolean", const: true },
          duplicate: { type: "boolean" },
          processing: { type: "boolean" },
        },
      }
    : {
        ...applyResponseEnumContracts(inferSchema(success.example, true), key),
        required: Object.keys(success.example),
      };

  applyTicketResponseSchemaContracts(successSchema, ticketResponseSchemaContracts[key]);

  if (key === "POST /events/{id}/orders") {
    const dataSchema = (successSchema.properties as Record<string, Record<string, unknown>>).data!;
    const rawOrderSchema = ticketResponseSchemaContracts[key]?.["data.order"];
    if (!rawOrderSchema) throw new Error("Missing ticket order response schema contract");

    dataSchema.oneOf = [
      {
        type: "object",
        additionalProperties: false,
        required: ["order", "checkoutUrl", "accessCode", "publicKey", "charge"],
        properties: {
          order: rawOrderSchema,
          checkoutUrl: { type: "string", format: "uri" },
          accessCode: { type: "string" },
          publicKey: { type: "string" },
          charge: {
            type: "object",
            additionalProperties: false,
            required: ["ticketSubtotalKobo", "platformFeeKobo", "totalPayableKobo"],
            properties: {
              ticketSubtotalKobo: { type: "integer", minimum: 0 },
              platformFeeKobo: { type: "integer", minimum: 0 },
              totalPayableKobo: { type: "integer", minimum: 0 },
            },
          },
        },
      },
      {
        type: "object",
        additionalProperties: false,
        required: ["order", "qrToken"],
        properties: {
          order: rawOrderSchema,
          qrToken: { type: "string", minLength: 32, maxLength: 4096 },
        },
      },
    ];
    delete dataSchema.properties;
    delete dataSchema.required;
  }

  if (key === "POST /tickets/{orderNumber}/checkout") {
    const dataSchema = (successSchema.properties as Record<string, Record<string, unknown>>).data!;
    const orderSchema = ticketResponseSchemaContracts[key]?.["data.order"];
    dataSchema.oneOf = [
      {
        type: "object", additionalProperties: false,
        required: ["outcome", "order", "checkoutUrl"],
        properties: {
          outcome: { type: "string", const: "checkout_ready" },
          order: {
            ...orderSchema,
            properties: {
              ...(orderSchema?.properties as Record<string, unknown>),
              status: { type: "string", const: "pending" },
            },
          },
          checkoutUrl: { type: "string", format: "uri", pattern: "^https://checkout\\.paystack\\.com/" },
        },
      },
      {
        type: "object", additionalProperties: false,
        required: ["outcome", "order"],
        properties: {
          outcome: { type: "string", const: "already_paid" },
          order: {
            ...orderSchema,
            properties: {
              ...(orderSchema?.properties as Record<string, unknown>),
              status: { type: "string", const: "paid" },
            },
          },
        },
      },
    ];
    delete dataSchema.properties;
    delete dataSchema.required;
  }

  const idempotentOrderExample = key === "POST /events/{id}/orders"
    ? {
        success: true,
        message: "Ticket order already initialized",
        data: {
          order: success.example.data && (success.example.data as Record<string, unknown>).order,
          checkoutUrl: success.example.data && (success.example.data as Record<string, unknown>).checkoutUrl,
        },
      }
    : undefined;

  if (key === "GET /locations/search") {
    const data = (successSchema.properties as Record<string, Record<string, unknown>>).data!;
    const results = (data.properties as Record<string, Record<string, unknown>>).results!;
    const suggestion = results.items as Record<string, unknown>;
    const fields = suggestion.properties as Record<string, Record<string, unknown>>;
    suggestion.required = ["id", "name", "label", "address", "latitude", "longitude", "state", "localArea"];
    fields.state = { type: ["string", "null"] };
    fields.localArea = { type: ["string", "null"] };
    data.required = ["results", "attribution"];
  }

  const pendingReviewExample = key === "POST /events/{id}/publish"
    ? (() => {
        const data = success.example.data as { event: Record<string, unknown> };
        const {
          moderation: _moderation,
          approvedAt: _approvedAt,
          publishedAt: _publishedAt,
          ...pendingEvent
        } = data.event;
        return {
          success: true,
          message: "Event submitted for manual review because automatic review is unavailable",
          data: {
            event: { ...pendingEvent, status: "pending_approval" },
          },
        };
      })()
    : undefined;

  const checkInPreviewNotFoundResponse = key === "POST /events/{eventId}/check-ins/verify"
    ? {
        description: "The event is unavailable to this organizer, or the QR token is not a paid ticket for this event.",
        content: {
          "application/json": {
            schema: {
              type: "object",
              additionalProperties: false,
              required: ["success", "error", "requestId"],
              properties: {
                success: { type: "boolean", const: false },
                error: {
                  type: "object",
                  additionalProperties: false,
                  required: ["code", "message"],
                  properties: {
                    code: { type: "string", enum: ["INVALID_TICKET", "EVENT_NOT_FOUND"] },
                    message: { type: "string" },
                  },
                },
                requestId: { type: "string" },
              },
            },
            examples: {
              invalidTicket: {
                summary: "Invalid, unpaid, or wrong-event QR token",
                value: {
                  success: false,
                  error: { code: "INVALID_TICKET", message: "Ticket is invalid" },
                  requestId: "req_01J2EXAMPLE9G7TZ8K4X3",
                },
              },
              eventNotFound: {
                summary: "Event unavailable to this organizer",
                value: {
                  success: false,
                  error: { code: "EVENT_NOT_FOUND", message: "Event was not found" },
                  requestId: "req_01J2EXAMPLE9G7TZ8K4X3",
                },
              },
            },
          },
        },
      }
    : undefined;

  const operation: Record<string, unknown> = {
    tags: [endpoint.tag],
    summary: endpoint.summary,
    description: endpoint.description,
    operationId: `${endpoint.method}_${endpoint.path.replace(/[^a-zA-Z0-9]+/g, "_")}`,
    parameters,
    security: endpoint.auth ? [{ bearerAuth: [] }] : [],
    responses: {
      [String(success.status)]: {
        description: success.description,
        content: {
          "application/json": {
            schema: successSchema,
            ...(success.examples ? {
              examples: Object.fromEntries(Object.entries(success.examples).map(([name, example]) => [name, {
                summary: example.summary,
                value: example.value,
              }])),
            } : { example: success.example }),
          },
        },
      },
      ...(idempotentOrderExample ? {
        "200": {
          description: "An idempotent retry returns the existing order and its checkout URL when available.",
          content: {
            "application/json": {
              schema: {
                type: "object",
                additionalProperties: false,
                required: ["success", "message", "data"],
                properties: {
                  success: { type: "boolean", const: true },
                  message: { type: "string" },
                  data: {
                    type: "object",
                    additionalProperties: false,
                    required: ["order"],
                    properties: {
                      order: ticketResponseSchemaContracts[key]?.["data.order"],
                      checkoutUrl: { type: "string", format: "uri" },
                    },
                  },
                },
              },
              example: idempotentOrderExample,
            },
          },
        },
      } : {}),
      ...(pendingReviewExample ? {
        "202": {
          description: "Event remains pending for manual review because Groq moderation is unavailable.",
          content: {
            "application/json": {
              schema: successSchema,
              example: pendingReviewExample,
            },
          },
        },
      } : {}),
      "400": key === "POST /tickets/{orderNumber}/checkout"
        ? checkoutErrorResponse("Idempotency-Key is missing or invalid", {
            invalidKey: { summary: "Required action key is missing or malformed", code: "IDEMPOTENCY_KEY_REQUIRED", message: "A valid Idempotency-Key header is required" },
          })
        : { $ref: "#/components/responses/BadRequest" },
      "401": { $ref: "#/components/responses/Unauthorized" },
      "403": { $ref: "#/components/responses/Forbidden" },
      "404": key === "POST /tickets/{orderNumber}/checkout"
        ? checkoutErrorResponse("Order not found or not owned by the buyer", {
            notFound: { summary: "Missing or unowned order", code: "TICKET_ORDER_NOT_FOUND", message: "Ticket order was not found" },
          })
        : checkInPreviewNotFoundResponse || { $ref: "#/components/responses/NotFound" },
      "409": key === "POST /tickets/{orderNumber}/checkout"
        ? checkoutErrorResponse("Checkout cannot safely continue", {
            processing: { summary: "Paystack status is processing or uncertain", code: "PAYMENT_STILL_PROCESSING", message: "Ticket payment is still being confirmed" },
            notRetryable: { summary: "Order or reservation cannot be retried", code: "TICKET_ORDER_NOT_RETRYABLE", message: "Ticket order cannot be retried" },
          })
        : { $ref: "#/components/responses/Conflict" },
      "415": { $ref: "#/components/responses/UnsupportedMediaType" },
      "422": { $ref: "#/components/responses/ValidationError" },
      "429": { $ref: "#/components/responses/RateLimited" },
      "500": { $ref: "#/components/responses/ServerError" },
      ...(key === "POST /tickets/{orderNumber}/checkout" ? {
        "503": checkoutErrorResponse("Per-order financial lock is unavailable", {
          lockUnavailable: { summary: "Redis financial lock unavailable", code: "FINANCIAL_LOCK_UNAVAILABLE", message: "This operation is temporarily unavailable" },
        }),
      } : {}),
      ...(key === "GET /locations/search" ? {
        "502": { $ref: "#/components/responses/BadGateway" },
        "503": { $ref: "#/components/responses/ServiceUnavailable" },
      } : {}),
    },
    ...(endpoint.roles ? { "x-required-roles": endpoint.roles } : {}),
  };

  if (endpoint.requestBody) {
    const body = requestBodyContracts[key];
    if (!body) {
      throw new Error(`Missing OpenAPI request-body contract for ${key}`);
    }

    operation.requestBody = {
      required: true,
      description: body.description,
      content: {
        [body.contentType]: {
          schema: applyRequestBodyEnumContracts(
            applyRequestBodySchemaContracts(body.schema, key),
            key,
          ),
          example: body.example,
        },
      },
    };
  }

  paths[endpoint.path] = {
    ...(paths[endpoint.path] || {}),
    [endpoint.method]: operation,
  };
}

paths["/health"] = {
  get: {
    tags: ["System"],
    summary: "Health check",
    description: "Confirms that the HTTP process is running. It does not disclose credentials or provider configuration.",
    servers: [{ url: env.APP_BASE_URL }],
    security: [],
    responses: {
      "200": {
        description: "Service process is running",
        content: {
          "application/json": {
            schema: {
              type: "object",
              required: ["success", "service", "status", "timestamp"],
              properties: {
                success: { type: "boolean", const: true },
                service: { type: "string" },
                status: { type: "string", const: "ok" },
                timestamp: { type: "string", format: "date-time" },
              },
            },
            example: {
              success: true,
              service: "community-connect-api",
              status: "ok",
              timestamp: "2026-07-18T09:30:00.000Z",
            },
          },
        },
      },
    },
  },
};

const errorExample = (code: string, message: string, details?: unknown) => ({
  success: false,
  error: {
    code,
    message,
    ...(details === undefined ? {} : { details }),
  },
  requestId: "req_01J2EXAMPLE9G7TZ8K4X3",
});

const reusableErrors: Array<[string, number, string, Record<string, unknown>]> = [
  ["BadRequest", 400, "Bad request", errorExample("BAD_REQUEST", "The request could not be processed.")],
  ["Unauthorized", 401, "Authentication failed", errorExample("AUTHENTICATION_REQUIRED", "A valid access token is required.")],
  ["Forbidden", 403, "Authorization failed", errorExample("FORBIDDEN", "You are not allowed to perform this operation.")],
  ["NotFound", 404, "Resource not found", errorExample("RESOURCE_NOT_FOUND", "The requested resource was not found.")],
  ["Conflict", 409, "Resource state conflict", errorExample("RESOURCE_CONFLICT", "The resource is not in a valid state for this operation.")],
  ["UnsupportedMediaType", 415, "Unsupported media type", errorExample("UNSUPPORTED_IMAGE_TYPE", "Only JPEG, PNG, and WebP images are allowed.")],
  ["ValidationError", 422, "Zod validation failed", errorExample("VALIDATION_ERROR", "Request validation failed.", [{ path: "body.amountKobo", message: "Expected a positive integer" }])],
  ["RateLimited", 429, "Rate limit exceeded", errorExample("RATE_LIMITED", "Too many requests. Try again later.")],
  ["ServerError", 500, "Unexpected server error", errorExample("INTERNAL_SERVER_ERROR", "The request could not be completed.")],
  ["BadGateway", 502, "Location provider error", errorExample("LOCATION_PROVIDER_UNAVAILABLE", "Location search is temporarily unavailable")],
  ["ServiceUnavailable", 503, "Location search is not configured", errorExample("LOCATION_SEARCH_UNAVAILABLE", "Location search is unavailable")],
];

export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Community Connect API",
    version: "1.1.0",
    description: "Secure REST and realtime backend for events, communities, chat, AI, wallet, notifications, and disputes. Every operation includes request and response schemas, accepted enum values for constrained fields, and examples. Money is represented in integer kobo.",
  },
  servers: [
    { url: `${env.APP_BASE_URL}${env.API_PREFIX}`, description: env.NODE_ENV },
  ],
  tags: [...new Set(apiEndpoints.map((endpoint) => endpoint.tag))].map((name) => ({ name })),
  paths,
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "JWT",
        description: "Short-lived access token. Refresh tokens are accepted only by /auth/refresh and /auth/logout.",
      },
    },
    schemas: {
      SuccessResponse: {
        type: "object",
        required: ["success", "message"],
        properties: {
          success: { type: "boolean", const: true },
          message: { type: "string" },
          data: { type: ["object", "array", "null"] },
        },
      },
      ErrorResponse: {
        type: "object",
        required: ["success", "error", "requestId"],
        properties: {
          success: { type: "boolean", const: false },
          error: {
            type: "object",
            required: ["code", "message"],
            properties: {
              code: { type: "string" },
              message: { type: "string" },
              details: {},
            },
          },
          requestId: { type: "string" },
        },
      },
    },
    responses: Object.fromEntries(
      reusableErrors.map(([name, status, description, example]) => [
        name,
        {
          description,
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/ErrorResponse" },
              example,
            },
          },
          "x-status-code": status,
        },
      ]),
    ),
  },
};
